[package]
name = "bruteforce-rist"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]

[dependencies]
byteorder = "1.0.0"
openssl-sys = "0.9.12"
rayon = "0.7.0"
rust-crypto = "0.2.36"
