[package]
name = "solve_sssp"
version = "0.1.0"
authors = ["Avi Weinstock <aweinstock314@gmail.com>"]

[dependencies]
#permutohedron = "0.2.2"
fnv = "1.0.3"
#mersenne_twister = "1.1.0"
rand = "*"
rayon = "0.8.2"

[profile.release]
lto = true
